/**
 * Numeric abort codes from the `waterx_perp` `error` module.
 * Use in integration / simulate assertions when matching `MoveAbort` / gRPC error metadata.
 */
export const WATERX_PERP_ABORT = {
  MARKET_NOT_ACTIVE: 100,
  SYMBOL_ALREADY_EXISTS: 101,
  SYMBOL_NOT_EXISTS: 102,
  SYMBOL_NOT_ACTIVE: 103,
  EXCEED_MAX_LEVERAGE: 104,
  EXCEED_MAX_OPEN_INTEREST: 105,
  INVALID_CONFIG: 106,

  POSITION_NOT_FOUND: 200,
  INVALID_SIZE: 201,
  INSUFFICIENT_COLLATERAL: 202,
  POSITION_NOT_LIQUIDATABLE: 203,
  TOO_MANY_LINKED_ORDERS: 204,
  USER_MISMATCH: 205,
  COOLDOWN_NOT_ELAPSED: 206,
  POSITION_FLIP_NOT_SUPPORTED: 207,
  INVALID_COLLATERAL_TYPE: 208,

  ORDER_NOT_FOUND: 300,
  INVALID_ORDER_TYPE: 301,
  INVALID_TRIGGER_PRICE: 302,
  REDUCE_ONLY_REQUIRES_POSITION: 303,
  INVALID_LINKED_ORDER: 304,

  POOL_NOT_ACTIVE: 400,
  TOKEN_NOT_SUPPORTED: 401,
  TOKEN_ALREADY_SUPPORTED: 402,
  INSUFFICIENT_LIQUIDITY: 403,
  EXCEED_CAPACITY: 404,
  SLIPPAGE_EXCEEDED: 405,
  INSUFFICIENT_DEPOSIT: 406,
  REDEEM_NOT_READY: 407,
  NO_REDEEM_REQUEST: 408,
  EXCEED_RESERVE_RATIO: 409,
  INSUFFICIENT_FREE_LIQUIDITY: 410,
  EXCEED_OI_CAP: 411,

  ZERO_PRICE: 500,
  STALE_PRICE: 501,

  NOT_ACCOUNT_OWNER: 600,
  INSUFFICIENT_BALANCE: 601,
  SUB_ACCOUNT_NOT_FOUND: 602,
  MAX_SUB_ACCOUNTS_REACHED: 603,
  SUB_ACCOUNT_NAME_TOO_LONG: 604,

  REFERRAL_ALREADY_BOUND: 700,
  SELF_REFERRAL: 701,
  INVALID_REFERRAL_CODE: 702,
  REFERRAL_CODE_BEING_SET: 703,
  REFERRAL_CODE_NOT_EXISTS: 704,

  UNAUTHORIZED: 800,
  INVALID_VERSION: 801,

  MISSING_REQUEST_WITNESS: 900,
  MISSING_RESPONSE_WITNESS: 901,
  POSITION_LOCKED: 902,
  TRADING_SLIPPAGE_EXCEEDED: 903,
  WITNESS_ALREADY_EXISTS: 904,
  INVALID_ACTION: 905,
} as const;

/** Parse `abort code: NNN` from gRPC / normalized integration error strings. */
export function parseWaterxAbortCodeFromMessage(message: string): number | undefined {
  const m = message.match(/abort code:\s*(\d+)/i);
  if (!m) return undefined;
  const n = Number(m[1]);
  return Number.isFinite(n) ? n : undefined;
}
